gnoverse/tlin

formatter/fmt_test.go, formatter/general.go, formatter/unnecessary_else.go, internal/fixer.go, internal/fixer_test.go, testdata/main.gno
Added a feature that suggests code modifications when it's possible to analyze the AST.
This feature demonstrates how the code could be improved. Additionally, I've included separate notes to explain how the code has changed and the resoning behind these decisions.
```plain
error: unnecessary-else
--> main.gno
|
6 |         if x {
7 |                return 1
8 |         } else {
9 |                return 2
10 |         }
| ~~~~~~~~~~
| unnecessary else block
Suggestion:
6 | if x {
7 |    return 1
8 | }
9 | return 2
Note: Unnecessary 'else' block removed.
The code inside the 'else' block has been moved outside, as it will only be executed when the 'if' condition is false.
```
=> Code suggestion

.github/workflows/go.yml, formatter/fmt.go, formatter/simplify_slice_expr.go, internal/engine.go, internal/lint.go, internal/lint_test.go, internal/types.go, testdata/slice0.gno
Simplify expression when specifying lengths with the `len` function inside a slice.
Handling these cases:
```go
slice[:len(slice)] → slice[:]
slice[n:len(slice)] → slice[n:] // n: number literal
slice[a:len(slice)] → slice[a:] // a: variable
```
```go
package slice
var slice = []int{1, 2, 3}
func foo() {
_ = slice[1:len(slice)]
}
func bar() {
_ = slice[:len(slice)]
}
func baz() {
a := 1
_ = slice[a:len(slice)]
}
```
Linter result:
```plain
error: simplify-slice-range
--> testdata/slice0.gno
|
6 |         _ = slice[1:len(slice)]
|      ^ unnecessary use of len() in slice expression, can be simplified
Suggestion:
6 | slice[1:]
Note: unnecessary use of len() in slice expression, can be simplified
Here, `slice[1:len(slice)]` can be simplified to `slice[1:]`. When slicing to the end of a …
```
=> simplify slice expr (avoid len)

formatter/fmt.go, formatter/fmt_test.go, formatter/unnecessary_type_conv.go, internal/engine.go, internal/lint.go, internal/lint_test.go, testdata/conv0.gno, testdata/demo.gno
Implemented `UnnecessaryConversionRule` to detect redundant type conversions. This rule identifies cases where a variable is converted to its own type.
=> Add Unnecessary Type Conversion Lint Rule

cmd/tlin/main.go, formatter/fmt.go, formatter/fmt_test.go, formatter/general.go, formatter/simplify_slice_expr.go, formatter/unnecessary_else.go, formatter/unnecessary_type_conv.go, internal/dfa/dfa.go, internal/engine.go, internal/fixer.go, internal/lints/default_golangci.go, internal/lints/lint_test.go, internal/lints/loop_allocation.go, internal/lints/simplify_slice_expr.go, internal/lints/unncessary_type_conversion.go, internal/lints/unnecessary_else.go, internal/lints/unused_function.go, internal/rule_set.go, internal/types/types.go, testdata/loop_alloc0.gno
- Detect unneccesary memory allocation, especially declare new variables inside the loop conditions.
Introduce [DFA](https://en.wikipedia.org/wiki/Data-flow_analysis) (data Flow Analysis) to achieve the advancing static analysis.
=> check basic memory allocation inside loop

formatter/fmt.go, formatter/general.go, formatter/slice_bound.go, internal/engine.go, internal/lints/lint_test.go, internal/lints/slice_bound.go, internal/rule_set.go, internal/types/types.go, testdata/bound/bound0.gno, testdata/bound/bound1.gno, testdata/bound/bound2.gno
Added detect potential slice boundary violations lint
- Inspect index accesses to slices or arrays and slice expressions
- Detect potentially dangerous accesses without boundary checks
=> feat: Slice Out-of-Bound Check

internal/lints/detect_cycle_test.go, internal/lints/detect_cycles.go
1. Modified `analyzeFuncDecl`:
- Ignores self-calls when building the dependency graph.
- This prevents direct recursion from being mistaken for a cycle.
2. Update `dfs`:
- Added a check to ignore direct self-reference during cycle delection.
Still correctly identifies indirect cycles (e.g., A -> B -> A).
=> fix: Cycle Detection to Ignore Direct Recursion

internal/lints/lint_test.go, internal/lints/slice_bound.go, testdata/bound/bound3.gno
1. Extended `isWithinSafeContext` function to recognize safe slice manipulations within range loops.
2. Added `isRangeIndexSlice` function to detect slice expressions using range loop indices.
3. Implemented `isRangeIndexInSlice` to check for range index usage in slice bounds and ellipsis.
4. Created `isRangeIndexExpr` for recursive checking of range index usage in complex expressions.
These improvements allow the lint to safely ignore common patterns such as:
- `arr[:i]`
- `arr[i+1:]`
- `arr[i:]`
- `append(arr[:i], arr[i+1:]...)`
=> fix: Improve slice bounds check lint for range loop contexts

internal/engine.go, internal/lints/lint_test.go, internal/lints/useless_break.go, internal/rule_set.go, testdata/break/break0.gno, testdata/break/break1.gno, testdata/break/break2.gno
Add new lint rule to detect useless break statement in `switch` and `select` (go specific) clauses.
This lint works as follows:
1. It traverses the AST of the given file.
2. For each switch or select statement encountered:
- It examines each case clause.
- If the last statement in a case clause is an unabled break, it's flagged as useless.
3. Each useless break detected is reported.
- No useless breaks
- Useless breaks in switch statements
- Useless breaks in select statements
- Labeled breaks (which are not considered useless)
=> feat: Detect useless break

formatter/builder.go, formatter/cyclomatic_complexity.go, formatter/early_return.go, formatter/format_emit.go, formatter/formatter_test.go, formatter/general.go, formatter/simplify_slice_expr.go, formatter/slice_bound.go, formatter/unnecessary_type_conv.go
Defined `headerType` for each issue to show their importance. Currently, 2 types have been added: `warnign` and `error`.
The `warning` type is applied to common lints that are not major problems. The `error` type is used when rendering lint rules related to golangci-lint or memory issues.
=> feat: Issue-Specific Header Type

formatter/builder.go, formatter/defers.go, internal/engine.go, internal/lints/defers.go, internal/lints/defers_test.go, internal/rule_set.go, testdata/defer/defer0.gno, testdata/defer/defer1.gno, testdata/defer/defer2.gno
- detect calling `panic` inside `defer` statement
- detect deferring nil function
- prevent use of defer inside loop (range, for)
=> feat: defers

internal/engine.go, internal/engine_test.go
- Increase engine's test coverage
- Add some benchmarks
- refactor filterUndefinedIssues function, increase performace
BenchmarkFilterUndefinedIssues_Prev-8   	 4466745	       252.4 ns/op	    1344 B/op	       3 allocs/op
BenchmarkFilterUndefinedIssues_New-8    	10111783	       125.5 ns/op	     768 B/op	       1 allocs/op
PASS
=> feat(engine): Increase Test Coverage for engine

cmd/tlin/main.go, cmd/tlin/main_test.go, formatter/builder.go, formatter/formatter_test.go, internal/engine.go, internal/engine_test.go, internal/lints/default_golangci.go, internal/lints/lint_test.go, internal/symbol_table.go, internal/symbol_table_test.go, lint/lint.go, lint/lint_test.go
This PR adds a few things:
- process source instead of filename to generate issues
- refactor main.go to be used partially as a library by creating a lint.go file and making logs optional
- fix a little typo GenetateFormattedIssue instead of GenerateFormattedIssue
Some of this code is far from perfect for example:
```go
var node *ast.File
var err error
if content == nil {
node, err = parser.ParseFile(fset, filename, nil, parser.ParseComments)
} else {
node, err = parser.ParseFile(fset, filename, content, parser.ParseComments)
}
if err != nil {
return nil, nil, err
}
```
Which was created to "fix" the issue that nil wasn't taken into account when using parser.Parsefile with an indirect function argument
=> feat: generate issues from source and refactor to make it as a library

formatter/builder.go, formatter/formatter_test.go, internal/fixer/fixer_test.go
Improve snippet formatting by removing common indent prefix from code lines.
- Modify `AddCodeSnippet` builder function to remove the common indentation before displaying each line.
- Adjust underline positioning to match the new indentation:
- Update `AddUnderlineAndMessage` to account for the removed indentation level.
**Before**
Simplified output; dots are indicates the indentation
```plain
1 | ....if foo() {
2 | ........println()
3 | ....} 
```
**After**
```plain
1 | if foo()
2 | ....println()
3 | }
```
=> fix: Adjust Indent Position

internal/fixer/fixer.go, internal/fixer/fixer_test.go
Improve performance and memory usage in Fixer
```plain
old version:    9111        113605 ns/op        7812 B/op         138 allocs/op
new version:  10000        104953 ns/op        7317 B/op         133 allocs/op
```
- Execution time: 7.6% faster (104953 ns/op vs 113605 ns/op)
- Memory allocation: 6.3% reduction (7317 B/op vs 7812 B/op)
- Allocation count: 3.6% fewer allocations (133 allocs/op vs 138 allocs/op)
=> perf(fixer): enhance auto fix

.github/labeler.yml, README.md, docs/rfc/defer-checks.md, docs/rfc/early-return.md, docs/rfc/emit-event.md, docs/rfc/mod-tidy.md, docs/rfc/repeated-regex-compilation.md, docs/rfc/template.md, docs/rfc/unnecesary-slice-length.md, docs/rfc/unnecessary-break.md, docs/rfc/unnecessary-type-conversion.md
- Add RFC documentation for each lint rules
- Add RFC templates
- Updated README regarding adding lint rules to the README
=> doc: Addiding Documentation for Linting Rules

formatter/builder.go, formatter/deprecated.go, formatter/formatter_test.go, internal/checker/deprecate.go, internal/checker/deprecate_test.go, internal/engine.go, internal/lints/deprecate_func.go, internal/rule_set.go, testdata/deprecate/orig_caller.gno
Add a deprecated functon checker that identifies the usage and suggests a alternative functions if possible.
The core of this implementation is the `DeprecatedFuncChecker` struct type, which maintains a map of deprecated functions along with their alternative functions.
1. **Registration**: Deprecated functions are registered using thr `Register` method, which takes three parameters
- Package name
- Function name
- Alternative function (`packageName.funcName` format)
2. **Function Call Identification**: For each AST node, the checker looks for `*ast.CallExpr` nodes, which represent function calls.
3. **Selector Expression Analysis**: It then checks if the function call is a selector expression (`*ast.SelectorExpr`), which is typical for `package.Function()` calls.
4. **Package and …
=> feat: Deprecated Function Checker

internal/engine.go, internal/rule_set.go
fixes #93
This PR updates the default severity of all the rules based on the convention.
It also refactor how default rules are added by checking if the rule is set to SeverityOff
=> feat: default rules severity adjustments

docs/rfc/const-error-decl.md, docs/rfc/template.md, internal/engine.go, internal/lints/const_error_decl.go, internal/lints/lint_test.go, internal/rule_set.go, testdata/const-error-decl/const_decl.gno, testdata/const-error-decl/const_decl_multiple.gno, testdata/const-error-decl/var_decl.gno
Detect and report the use of `const` for declaring errors created with `errors.New()`.
=> feat: Prevent Constant Error Declaration

formatter/builder.go, formatter/formatter_test.go
Output the location along with the file name when printing the header.
At first, I thought it was unnecessary because the code lines are printed together with line numbers at the bottom, but it turned out to be harder to recognize than expected.
**Before**
```plain
error: simplify-slice-range
--> slice0.gno
```
**After**
```plain
error: simplify-slice-range
--> slice0.gno:10:6
```
=> chore(formatting): Print Line Position in to Header

formatter/builder.go, formatter/cyclomatic_complexity.go, formatter/formatter_test.go, formatter/general.go, internal/lints/const_error_decl.go, internal/lints/cyclomatic_complexity.go, internal/lints/defers.go, internal/lints/deprecate_func.go, internal/lints/detect_cycles.go, internal/lints/early_return.go, internal/lints/early_return_test.go, internal/lints/format_emit.go, internal/lints/lint_test.go, internal/lints/loop_allocation.go, internal/lints/missing_package_mod.go, internal/lints/simplify_slice_expr.go, internal/lints/slice_bound.go, internal/lints/unncessary_type_conversion.go
The colors and format have been adjusted for the lint result output.
=> adjust format

README.md, cmd/tlin/main.go, cmd/tlin/main_test.go, internal/engine.go, internal/engine_test.go, lint/lint.go, lint/lint_test.go
fixes #108
Add a ignore argument to ignore paths / files
=> feat: argument to ignore paths / files

fixer_v2/engine.go, fixer_v2/query/hole.go, fixer_v2/query/hole_test.go, fixer_v2/query/lexer.go, fixer_v2/query/meta_variable_test.go, fixer_v2/query/parser.go, fixer_v2/query/type.go
A hole pattern is a special syntax used in pattern matching that acts as a placeholder or "wildcard" in a pattern. Think of it as a variable that can match and capture different parts of code while searching through source code.
```go
// Pattern with holes
if :[[condition]] {
:[[body]]
}
// Can match code like:
if x > 0 {
return true
}
// Or:
if isValid(user) {
doSomething()
}
```
1. Added support for typed hole patterns with format `:[[name:type]]`
2. Implemented quantifier support for hole patterns (`*`, `+`, `?`)
3. Enhanced lexer to properly parse and tokenize new pattern syntax
4. Added hole configuration system to manage pattern types and quantifiers
5. Updated parser to handle the new hole types and configurations
6. Added comprehensive test coverage for new features
| Syntax | …
=> feat(fixer_v2): Hole Pattern Syntax for Pattern Matching

.github/golangci.yml, Makefile, fixer_v2/query/internal.go, fixer_v2/query/internal_test.go
~~~mermaid
stateDiagram-v2
direction LR
GO --> CL: "COLON"
CL --> OB: "["
OB --> DB: "["
OB --> NM: "ident"
DB --> NM: "ident"
%% Simple Pattern :[name]
NM --> NM: "ident"
NM --> CB: "]"
CB --> OK: "COLON" or "whitespace"
CB --> QB: "]"
CB --> QT: "*+?"
%% Type Pattern :[[name:type]]
NM --> ID: "COLON"
ID --> ID: "ident"
ID --> CB: "]"
%% Post Quantifier
QB --> QT: "*+?"
QB --> OK: "COLON" or "whitespace"
QT --> OK: "COLON" or "whitespace"
%% Text handling
GO --> TX: "other"
GO --> WS: "whitespace"
GO --> BR: "{}"
%% Whitespace loop
WS --> WS: "whitespace"
WS --> CL: "COLON"
WS --> TX: "other"
WS --> BR: "{}"
%% Block handling
BR --> BR: "{"
BR --> OK: "}"
BR --> CL: "COLON"
BR --> WS: "whitespace"
note right of GO
Initial state
end note
note right of CL
After colon
end note
note right of …
=> feat(fixer_v2): State Transition Machine for Metavariable Parser

fixer_v2/query/buffer.go, fixer_v2/query/buffer_test.go, fixer_v2/query/hole_test.go, fixer_v2/query/internal.go, fixer_v2/query/parser.go
Added a new buffer implementation using state machine based parsing for meta-variables.
=> feat(fixer_v2): Implement state machine based buffer for meta-variable parsing

README.md, cmd/tlin/main_test.go, internal/engine.go, internal/lints/default_golangci.go, internal/lints/gno_analyzer.go, internal/lints/regex_lint_test.go, internal/lints/repeated_regex_compilation.go, internal/rule_set.go
fixed #92
This PR propose a new simpler implementation of LintRule to create a new rule easier than before.
ps: be harsh with the PR to have some good foundations to build upon
=> refactor: rule type

internal/nolint/nolint.go, internal/nolint/nolint_test.go
Improve `nolint` comment scope detection and inline comment handling.
**Key changes:**
1. Enhanced inline comment detection
- Updated `isInlineComment` function to determine inline status based on file offsets
- A comment is considered inline if it appears after a statement on the same line
- Example: In `fmt.Println("foo") //nolint:rule1`, the comment is properly
detected as inline since it follows the statement
2. Refined scope determination rules
- For standalone comments (without code), the scope extends from the comment line
through the end of the next statement
- Comments appearing before the package declaration now apply to the entire file
3. Refactored
- Changed some type and variable names
=> refactor, fix(nolint): Enhance Inline Detection

fixer_v2/lexer.go, fixer_v2/lexer_test.go, fixer_v2/matcher.go, fixer_v2/parser.go
Improves the `Lex` function to correctly tokenize multi-line input by ensuring each line is stored as a separate `TokenLiteral`.
1. Flush literals correctly when encountering new lines (`\n`)
- Previously, multi-line literals were stored as a single token, causing incorrect `Line` values.
- Now, each line is treated as a separate token, improving consistency.
2. Ensure correct `Line` and `Col` tracking
- `Col` now resets to `0` after a line break.
- `Line` properly increments when encountering `\n`.
3. Preserve explicit newline tokens (`\n`)
- This ensures that structural line breaks in the source code are retained in tokenization.
=> feat: Improve Lexing for Multi-line Tokenization

internal/lints/gno_analyzer.go, internal/lints/gno_analyzer_test.go
closes #134 
```plain
warning: unused-import
--> testdata/pkg/pkg0.gno:6:5
|
6 | "strings" // unused import
| ^
|
= unused import: strings
```
=> fix: Display line information in `unused-import` checks

internal/lints/simplify_for_range.go, internal/lints/simplify_for_range_test.go, internal/rule_set.go, internal/types/analyzer.go, internal/types/types.go, testdata/simple_for/for0.gno, testdata/simple_for/for1.gno, testdata/simple_for/for2.gno, testdata/simple_for/for3.gno, testdata/simple_for/for4.gno, testdata/simple_for/for5.gno, testdata/simple_for/for6.gno
Added a new lint rule that detects counter-based for loops that can be simplified to range-based loops.
The rule analyzes for loops and suggests simplifying them from:
```go
for i := 0; i < n; i++ {
// body
}
```
to:
```go
for i := range n {
// body  
}
```
The analyzer performs the following checks:
1. Validates loop structure:
- Initialize statement must be `i := 0`
- Condition must be `i < n` (less than operator)
- Post statement must be `i++`
- Variable names must be consistent across all parts
2. Additional safety checks:
- Loop variable must not be modified inside the loop body
- Loop range must not be a function call (must be iterable)
- Loop variable must not be used after the loop
- Initial value must be 0
Input:
```go
for i := 0; i < 5; i++ {
println(i)
}
```
Output suggestion: …
=> feat: simplify for loop

internal/lints/early_return.go, internal/lints/early_return_test.go, testdata/early_return/a2.gno, testdata/early_return/a3.gno, testdata/early_return/a4.gno, testdata/early_return/a5.gno, testdata/early_return/a6.gno
Improves the early-return linter rule by addressing issues with nested if–else structures and duplicate suggestions. Instead of treating each if or else separately, we now model if–else chains as a binary tree (`IfChain`), enabling more robust AST transformations.
- **Binary Tree Model:**  
Introduce an `IfChain` structure to represent nested if–else (and else-if) constructs as a binary tree. This abstraction helps capture the complete condition chain.
- **Tree Pruning:**  
Implement pruning to mark and skip inner if–else nodes once the parent chain has been processed. This prevents duplicate suggestions from nested nodes.
- **If Flattening:**  
Add a flattening algorithm that transforms nested if–else chains into a clean early-return style. For example, it converts:
```go
if x > 10 { …
```
=> fix: early return v2

internal/lints/gno_analyzer.go, internal/lints/simplify_slice_expr.go, internal/lints/tokens.go, testdata/slice1.gno
Update a lint rule that detects and suggests simplifications for unnecessary `len()` usage in slice expressions. The implementation is based on the Go standard library's `simplifyslice` analyzer, but adapted to work within our linting framework.
1. **Enhanced Type Checking**
- Added explicit checks for 3-index slices (`s[low:high:max]`)
- Improved validation of slice expressions to ensure they're valid for simplification
- Added checks for locally defined `len` functions to avoid false positives
2. **Improved Error Detection**
- More comprehensive validation of slice expression components
- Better handling of edge cases and invalid expressions
- Clearer separation of different simplification scenarios
3. **Fixed Suggestion Formatting**
- Corrected operator handling in suggestions to …
=> fix: Update Slice Expression Simplifier
